"use strict";
exports.__esModule = true;
var noteHandlers_1 = require("./packages/noteHandlers/noteHandlers");
var storage_1 = require("./packages/storage/storage");
var apiRoutes_1 = require("./packages/api/apiRoutes");
var Server = require('socket.io').Server;
var cors = require('cors');
var express = require('express');
var app = express();
var port = 3999;
var memoryStorage = new storage_1.MemoryStorage();
app.use(cors());
app.use(express.json());
(0, apiRoutes_1.registerApiRoutes)(app, memoryStorage);
var io = new Server(app.listen(port, function () { return console.log('Server is started on: ', port); }), { cors: '*' });
io.on('connection', function (socket) {
    var userName = socket.handshake.query.userName || null;
    console.log('Got connection from: ', userName);
    (0, noteHandlers_1.registerNoteHandlers)(io, socket, memoryStorage);
});
